### PR TITLE
Testen on/off button for blinds (experimental)

### PR DESCRIPTION
**Pull request by lvhv91**

### CODE REVIEW

**Comment by lvhv91** [comment]
Dependabot (https://dependabot.com/) might be useful for auto-updating the dependencies.

**Comment by lvhv91** [comment]
Hi Rogier, 

Can you push the latest version to the Homey app store?

**Comment by djbarney** [comment]
Tested this through CLI install on my homey with 2 fyrtur blinds, works great! thanks @lvhv91 for adding this!

**Comment by rogierhofboer** [comment]
Good news. Last night I took my Tradfri gateway out of the dust and connectednslme lights and remotes. This weekend I will test the changes of lvhv91 myself and will create a new version. 
@lvhv91: in case you didn't already, please add yourself as co-author in the app json using the credentials you prefer.

**Pull request merged**
