### PR TITLE
Added group support (incl moods)

### PR DESCRIPTION
**Pull request by slasktrat**
Hi.

Funny, I was just about to create an app for the IKEA Trådfri Gateway when I found out you had done the same just a few days ago. So instead of starting from scratch I've extended this to include support for groups and moods via flow action.

### CODE REVIEW

**Comment by rogierhofboer** [comment]
Hi Espen,

Thanks for your PR. Since the app is still alpha, I've merged it without thorough review. I also still have to resolve the issue I can't turn off lights anymore (probably after turning them on via a flow), but didn't found the

**Comment by rogierhofboer** [comment]
@slasktrat I have published a new alpha version of the app, including your changes and added you to the alpha testers.

**Comment by rogierhofboer** [comment]
I think this is also the cause of issue #1 , I did some testing with reconnecting by rebooting the gateway, but obviously this doesn't cover all cases. I will look at it at a later moment, but of course you are welcome to help.

**Comment by rogierhofboer** [comment]
Also I checked if it reconnected and I could operate lights after that, but might have missed events not coming in anymore

**Comment by slasktrat** [comment]
Yes, that might be. I will try to take a look at it a little later. We probably need some connection state validation e.g. in the "connection alive" callback. And maybe re-init the observers.

**Comment by slasktrat** [comment]
BTW, for debug I use homey-syslog to get logs besides output from athom cli.

**Comment by slasktrat** [comment]
A little update. I had some stability issues right after I paired a lot of new lamps with the trådfri gateway, but after that settled everything has worked 100% after that and is rock solid. :)

**Pull request merged**
